/* Match Studio — second-level case library */
(function () {
  'use strict';
  var DATA = { cases: [] }, lang = 'zh', activeCapability = 'all';
  var I18N = {
    zh: { 'nav.services': '服务', 'nav.cases': '案例', 'nav.team': '团队', 'nav.capabilities': '能力', 'nav.cta': '预约咨询', 'library.eyebrow': '真实项目库', 'library.title': '全部案例', 'library.sub': '按能力浏览 Match Studio 的完整项目案例，查看从现场制作到 AI 共创的真实交付。', 'library.all': '全部能力', 'library.count': '共 {count} 个案例', 'case.intro': 'Case Intro', 'case.approach': 'Creative / Production Approach', 'case.viewApproach': '查看制作方式', 'case.back': '返回案例', 'case.media': '查看项目素材', 'case.mediaLabel': '项目素材', 'case.openVideo': '打开视频', 'modal.close': '关闭', 'footer.tagline': '中国企业出海的全球内容制作伙伴', 'footer.col1': '工作室', 'footer.services': '服务', 'footer.cases': '案例', 'footer.col2': '公司', 'footer.team': '团队', 'footer.contact': '联系', 'footer.col3': '资源', 'footer.capabilities': '能力', 'footer.brief': '项目简报', 'footer.made': '为中国企业出海而生', 'library.empty': '这个能力暂时没有公开案例。' },
    en: { 'nav.services': 'Services', 'nav.cases': 'Cases', 'nav.team': 'Team', 'nav.capabilities': 'Capabilities', 'nav.cta': 'Book a consult', 'library.eyebrow': 'Project library', 'library.title': 'All cases', 'library.sub': 'Browse the full Match Studio project library by capability, from field production to AI co-creation.', 'library.all': 'All capabilities', 'library.count': '{count} projects', 'case.intro': 'Case Intro', 'case.approach': 'Creative / Production Approach', 'case.viewApproach': 'View approach', 'case.back': 'Back to case', 'case.media': 'View project media', 'case.mediaLabel': 'Project media', 'case.openVideo': 'Open video', 'modal.close': 'Close', 'footer.tagline': 'The global content partner for outbound Chinese brands', 'footer.col1': 'Studio', 'footer.services': 'Services', 'footer.cases': 'Cases', 'footer.col2': 'Company', 'footer.team': 'Team', 'footer.contact': 'Contact', 'footer.col3': 'Resources', 'footer.capabilities': 'Capabilities', 'footer.brief': 'Project brief', 'footer.made': 'Built for Chinese brands going global', 'library.empty': 'No public cases are available for this capability yet.' }
  };
  var CAPABILITIES = {
    'field-live': { zh: '海外拍摄与直播', en: 'Overseas production & live' },
    'brand-marketing': { zh: '品牌营销', en: 'Brand marketing' },
    'video-production': { zh: '视频制作', en: 'Video production' },
    'ai-co-creation': { zh: '企业 AI 共创', en: 'Enterprise AI co-creation' }
  };
  var CAPABILITY_ORDER = ['field-live', 'brand-marketing', 'video-production', 'ai-co-creation'];
  var SERVICE_CAPABILITIES = { Field: 'field-live', Live: 'field-live', Video: 'video-production', AI: 'ai-co-creation' };
  var BRAND_INDUSTRY = /电商|汽车|智能家居|消费|科技|游戏|美妆|食品|乳业|饮料|咖啡|工业|内容平台|活动|半导体|医药/;
  var BRAND_TITLE = /发布会|盛典|造物节|双\s*11|商业广告|广告|Trailer|发布|体验营销|品牌|IP/;
  var INDUSTRY_EN = { '电商／零售': 'E-commerce / retail', '电商／体验营销': 'E-commerce / experiential marketing', '活动／展会／现场运营': 'Events / field operations', '汽车': 'Automotive', '数字内容／网文 IP': 'Digital content / web IP', '游戏／数字内容': 'Games / digital content', '美妆': 'Beauty', '消费品牌／美容': 'Consumer brand / beauty', '流媒体／纪录片': 'Streaming / documentary', '流媒体／真人秀纪录片': 'Streaming / reality documentary', '医疗／医学会议': 'Healthcare / medical congress', '科技／消费电子': 'Technology / consumer electronics', '国际纪录片': 'International documentary', '国际传播／纪录片': 'International communications / documentary', '智能家居／清洁电器': 'Smart home / floor care', '消费电子': 'Consumer electronics', '消费电子／家电': 'Consumer electronics / home appliances', '食品／快消': 'Food / FMCG', '乳业／快消': 'Dairy / FMCG', '饮料／快消': 'Beverage / FMCG', '饮料／消费品牌': 'Beverage / consumer brand', '医药／大健康': 'Pharma / health', '内容平台／大型活动': 'Content platform / large-scale event', '半导体／科技': 'Semiconductors / technology', '工业／消费产品': 'Industrial / consumer products', '政要／机构传播': 'Public affairs / institutional communications', '连锁咖啡／消费品牌': 'Coffee chain / consumer brand' };
  var TERM = { '京东': 'JD', '腾讯': 'Tencent', '快手': 'Kuaishou', '抖音': 'Douyin', '华为': 'Huawei', '追觅': 'Dreame', '奥迪': 'Audi', '瑞幸咖啡': 'Luckin Coffee', '优酷': 'Youku', '淘宝': 'Taobao', '天猫': 'Tmall', '欧洲医学会': 'European medical congress', '家有恶猫': 'My Cat from Hell', '探索新境': 'Exploration New Ground', '寻找王一博': 'Finding Wang Yibo', '七日世界': 'Once Human', '姜妍': 'Jiang Yan', '全 AI': 'Fully AI', '商业广告': 'Commercial', '四季中国': 'Seasons of China', '第二季': 'Season 2', '第一季': 'Season 1' };
  function t(key) { return I18N[lang][key] || key; }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (char) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]; }); }
  function fileUrl(file) { return file && (file.url || (file.thumbnails && file.thumbnails.large && file.thumbnails.large.url)); }
  function mediaFor(c) { return (c.hero || [])[0] || (c.gallery || [])[0] || null; }
  function imageFor(c) { return fileUrl(mediaFor(c)); }
  function isPortraitHero(c) { var media = mediaFor(c); return media && Number(media.width) > 0 && Number(media.height) > 0 && Number(media.height) / Number(media.width) >= 1.5; }
  function orderCases(list) { return list.slice().sort(function (a, b) { return Number(isPortraitHero(a)) - Number(isPortraitHero(b)); }); }
  function frameAttrs(c) { var media = mediaFor(c); if (!media || Number(media.width) <= 0 || Number(media.height) <= 0) return ' data-frame="standard"'; var portrait = isPortraitHero(c); return ' data-frame="' + (portrait ? 'portrait' : 'standard') + '" style="aspect-ratio:' + (portrait ? Number(media.width) + ' / ' + Number(media.height) : '3 / 4') + '"'; }
  function translate(value) { var out = String(value || ''); Object.keys(TERM).sort(function (a, b) { return b.length - a.length; }).forEach(function (key) { out = out.split(key).join(TERM[key]); }); return out.replace(/｜/g, ' — ').replace(/／/g, ' / '); }
  function capabilityKeys(c) { var explicit = Array.isArray(c.capabilities) ? c.capabilities.filter(function (key) { return CAPABILITIES[key]; }) : []; if (explicit.length) return Array.from(new Set(explicit)); var keys = (c.services || []).map(function (service) { return SERVICE_CAPABILITIES[service]; }).filter(Boolean); if (BRAND_INDUSTRY.test(c.industry || '') || BRAND_TITLE.test(c.title || '')) keys.push('brand-marketing'); return CAPABILITY_ORDER.filter(function (key) { return keys.indexOf(key) !== -1; }); }
  function capabilityLabel(key) { return CAPABILITIES[key] ? CAPABILITIES[key][lang] : key; }
  function capabilityLabels(c) { return capabilityKeys(c).map(capabilityLabel).join(' · '); }
  function publicClient(value) { var client = String(value || ''); return /^Open\s+—\s+Lux confirmed/i.test(client) ? '' : client; }
  function localized(c) { if (lang === 'zh') return { title: c.title, client: publicClient(c.client), capabilities: capabilityLabels(c), intro: c.intro.zh, approach: c.approach.zh }; var title = c.titleEn || translate(c.title); return { title: title, client: publicClient(title.split(' — ')[0]), capabilities: capabilityLabels(c), intro: c.intro.en, approach: c.approach.en }; }
  function applyStaticText() { document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.querySelectorAll('[data-i18n]').forEach(function (node) { var key = node.getAttribute('data-i18n'); node.textContent = t(key); }); document.querySelector('.lang-zh').classList.toggle('active', lang === 'zh'); document.querySelector('.lang-en').classList.toggle('active', lang === 'en'); }
  function renderFilters() { var box = document.getElementById('capabilityFilters'); box.innerHTML = ''; [['all', t('library.all')]].concat(CAPABILITY_ORDER.map(function (key) { return [key, capabilityLabel(key)]; })).forEach(function (item) { var button = document.createElement('button'); button.type = 'button'; button.className = 'library-filter' + (activeCapability === item[0] ? ' is-active' : ''); button.textContent = item[1]; button.addEventListener('click', function () { activeCapability = item[0]; renderFilters(); renderGrid(); }); box.appendChild(button); }); }
  function cardMarkup(c) { var x = localized(c), img = imageFor(c), mediaButton = c.gallery?.length || c.videos?.length ? '<button class="case-media" type="button">' + esc(t('case.media')) + ' ↗</button>' : ''; return '<div class="case-card-inner"><div class="case-face case-front"><div class="case-img' + (img ? '' : ' case-img-empty') + '"' + frameAttrs(c) + (img ? '' : ' data-empty="true"') + '>' + (img ? '<img src="' + esc(img) + '" alt="' + esc(x.title) + '" loading="lazy">' : '<span class="case-empty-mark">MS</span>') + '<button class="case-flip case-hero-flip" type="button">' + esc(t('case.viewApproach')) + ' ↗</button></div><div class="case-body"><div class="case-meta">' + (x.client ? '<span>' + esc(x.client) + '</span>' : '') + '<span>' + esc(x.capabilities) + '</span></div><h3 class="case-title">' + esc(x.title) + '</h3><span class="case-copy-label">' + esc(t('case.intro')) + '</span><p class="case-intro">' + esc(x.intro) + '</p></div></div><div class="case-face case-back"><div class="case-back-top"><span class="case-copy-label">' + esc(t('case.approach')) + '</span><button class="case-flip" type="button" aria-label="' + esc(t('case.back')) + '">↺</button></div><h3 class="case-title">' + esc(x.title) + '</h3><div class="case-back-copy"><span class="case-copy-label">' + esc(t('case.intro')) + '</span><p class="case-intro">' + esc(x.intro) + '</p><span class="case-copy-label">' + esc(t('case.approach')) + '</span><p class="case-approach">' + esc(x.approach) + '</p></div>' + mediaButton + '</div></div>'; }
  function renderGrid() { var grid = document.getElementById('libraryGrid'), allCases = orderCases(DATA.cases || []), filtered = activeCapability === 'all' ? allCases : allCases.filter(function (c) { return capabilityKeys(c).indexOf(activeCapability) !== -1; }); document.getElementById('libraryCount').textContent = t('library.count').replace('{count}', filtered.length); grid.innerHTML = ''; if (!filtered.length) { grid.innerHTML = '<div class="library-empty">' + esc(t('library.empty')) + '</div>'; return; } filtered.forEach(function (c) { var card = document.createElement('article'); card.className = 'case-card'; card.innerHTML = cardMarkup(c); card.addEventListener('click', function (event) { if (!event.target.closest('.case-media, .case-flip')) card.classList.toggle('is-flipped'); }); card.querySelectorAll('.case-flip').forEach(function (button) { button.addEventListener('click', function (event) { event.stopPropagation(); card.classList.toggle('is-flipped'); }); }); var media = card.querySelector('.case-media'); if (media) media.addEventListener('click', function (event) { event.stopPropagation(); openCaseDetail(c); }); grid.appendChild(card); }); }
  function openCaseDetail(c) { var x = localized(c), hero = imageFor(c), gallery = (c.gallery || []).map(fileUrl).filter(Boolean), images = [hero].concat(gallery).filter(Boolean), media = images.map(function (url) { return '<div class="library-media-item"><img src="' + esc(url) + '" alt="" loading="lazy"></div>'; }).join(''), videos = (c.videos || []).map(function (video) { var url = fileUrl(video); return '<div class="video-row"><span>' + esc(video.filename || 'Video') + '</span><a href="' + esc(url) + '" target="_blank" rel="noreferrer">' + esc(t('case.openVideo')) + ' ↗</a></div>'; }).join(''); document.getElementById('modalRoot').innerHTML = '<div class="modal-backdrop library-detail-backdrop"><div class="modal-card case-modal-card library-detail-modal" role="dialog" aria-modal="true"><button class="modal-close" type="button" aria-label="' + esc(t('modal.close')) + '">×</button>' + (hero ? '<div class="library-detail-hero"><img src="' + esc(hero) + '" alt="' + esc(x.title) + '"></div>' : '') + '<div class="modal-body"><div class="modal-kicker">' + esc(x.capabilities) + '</div><h3>' + esc(x.title) + '</h3>' + (x.client ? '<p class="modal-client">' + esc(x.client) + '</p>' : '') + '<p class="modal-intro">' + esc(x.intro) + '</p><div class="library-detail-copy"><div><span class="detail-label">' + esc(t('case.approach')) + '</span><p>' + esc(x.approach) + '</p></div></div>' + (media || videos ? '<div class="media-section">' + (media ? '<div class="library-media-grid">' + media + '</div>' : '') + (videos ? '<div class="video-list">' + videos + '</div>' : '') + '</div>' : '') + '</div></div></div>'; var root = document.getElementById('modalRoot'); root.querySelector('.modal-close').addEventListener('click', closeModal); root.querySelector('.modal-backdrop').addEventListener('click', function (event) { if (event.target === event.currentTarget) closeModal(); }); }
  function closeModal() { document.getElementById('modalRoot').innerHTML = ''; }
  function bind() { document.getElementById('langToggle').addEventListener('click', function () { lang = lang === 'zh' ? 'en' : 'zh'; applyStaticText(); renderFilters(); renderGrid(); }); document.addEventListener('keydown', function (event) { if (event.key === 'Escape') closeModal(); }); }
  function initCursor() { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || window.matchMedia('(pointer: coarse)').matches) return; document.body.classList.add('custom-cursor'); var dot = document.getElementById('cursorDot'), ring = document.getElementById('cursorRing'); window.addEventListener('mousemove', function (event) { dot.style.transform = 'translate(' + event.clientX + 'px,' + event.clientY + 'px) translate(-50%,-50%)'; ring.style.transform = 'translate(' + event.clientX + 'px,' + event.clientY + 'px) translate(-50%,-50%)'; }); }
  async function load() { try { var response = await fetch('data/cases.json?v=20260823-2', { cache: 'no-store' }); if (!response.ok) throw new Error('case data unavailable'); DATA = await response.json(); } catch (error) { console.warn(error.message); } applyStaticText(); renderFilters(); renderGrid(); }
  bind(); initCursor(); load();
})();
